sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8fvbSRk6TxwcsYKY6Q
    access-key-secret: 5Cx4iQWrbTjcMP6KR6qATAFfV0vCil
    bucket-name: skt-out2222
